version: '3.8'
services:

  web:
    restart: on-failure
    build: .
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    entrypoint: /entrypoint.sh

  db:
    restart: on-failure
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
        - 5442:5432
    env_file:
        - .env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
