# Generated by Django 3.1.7 on 2021-02-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210224_1439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dislike',
        ),
    ]
